"""create customer values table

Revision ID: 495a471908d7
Revises: 5d1595590282
Create Date: 2026-09-06 20:44:04.050976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495a471908d7'
down_revision: Union[str, Sequence[str], None] = '5d1595590282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_values',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_values')
    # ### end Alembic commands ###
