"""add transaction idempotency key

Revision ID: 5d1595590282
Revises: 959d43d96bd6
Create Date: 2026-09-06 12:40:23.975985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1595590282'
down_revision: Union[str, Sequence[str], None] = '959d43d96bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uq_transaction_customer_idempotency_key', 'transactions', ['customer_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_customer_idempotency_key', 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
